#!/usr/bin/env python

import json
import socket
import time


def jsonrpc_call(socket, id, method, params):
    payload = {
        "method": method,
        "params": params,
        "jsonrpc": "2.0",
        "id": id,
    }
    socket.send(json.dumps(payload).encode("ascii"))
    response = socket.recv(2048)
    response = json.loads(response.decode("ascii"))
    print(response)


def set_light_from_hsbk(socket, id, target, h, s, b, k, t):
    jsonrpc_call(socket, id, "set_light_from_hsbk", [
        target, h, s, b, k, t
    ])


def power_on(socket, id, target):
    jsonrpc_call(socket, id, "power_on", {"target": target})


def power_off(socket, id, target):
    jsonrpc_call(socket, id, "power_off", {"target": target})

if __name__ == "__main__":
    s = socket.create_connection(("localhost", 1234))
    h = 0
    id = 0
    nb = "d073d501a0d5"
    fugu = "d073d500603b"
    neko = "d073d5018fb6"
    target = "*"
    try:
        power_on(s, id, target)
        while True:
            h = (h + 5) % 360
            id += 1
            set_light_from_hsbk(s, id, target, h, 0.8, 0.1, 2500, 450)
            time.sleep(0.5)
    finally:
        power_off(s, id, target)
        s.close()
