IF (NOT HAVE_PROCTITLE)
    SET(CMAKE_REQUIRED_QUIET TRUE)
    SET(HAVE_PROCTITLE 0 CACHE INTERNAL "setproctitle found in libbsd")
    SET(HAVE_LIBBSD 0 CACHE INTERNAL "libbsd found")
    MESSAGE(STATUS "Looking for setproctitle")
    CHECK_FUNCTION_EXISTS("setproctitle" HAVE_PROCTITLE)
    IF (NOT HAVE_PROCTITLE)
        MESSAGE(STATUS "Looking for setproctitle - not found, falling back on libbsd")
        FIND_PACKAGE(LibBSD)
        IF (NOT LibBSD_FOUND)
            MESSAGE(STATUS "Couldn't find setproctitle, no fancy report in the process list")
        ELSE ()
            SET(HAVE_PROCTITLE 1 CACHE INTERNAL "setproctitle found in libbsd")
            SET(HAVE_LIBBSD 1 CACHE INTERNAL "libbsd found")
        ENDIF ()
    ELSE ()
        SET(HAVE_PROCTITLE 1 CACHE INTERNAL "setproctitle found on the system")
    ENDIF ()
    UNSET(CMAKE_REQUIRED_QUIET)
ENDIF ()
