FIND_PATH(LIBBSD_INCLUDE_DIR bsd.h PATH_SUFFIXES bsd)

FIND_LIBRARY(LIBBSD_LIBRARY bsd)
IF(LIBBSD_LIBRARY)
    SET(LibBSD_FOUND TRUE)
ENDIF()

INCLUDE(FindPackageHandleStandardArgs)

FIND_PACKAGE_HANDLE_STANDARD_ARGS(LibBSD DEFAULT_MSG LIBBSD_LIBRARY LIBBSD_INCLUDE_DIR)
