\ProvidesClass{lgtdslides}

\LoadClass[utf8x,xcolor={usenames,svgnames}]{beamer}

\RequirePackage{lmodern}
\RequirePackage{arev}
\RequirePackage{tgbonum}
\RequirePackage{inconsolata}
\RequirePackage[T1]{fontenc}
\RequirePackage[fixlanguage]{babelbib}

\useoutertheme{infolines}
\setbeamertemplate{navigation symbols}{}
\setbeamertemplate{bibliography item}[text]
\setbeamerfont{footnote}{size=\tiny}

\colorlet{fgcolor}{White}
\definecolor{BeamerBlue}{RGB}{49,56,172}
